### ISSUE TITLE
Installation does not work.

### ISSUE THREAD

**Issue by jeschkies** [alecthomas/go-check-sumtype#1]
Hi,

I really like the linter but neither

```
go install github.com/alecthomas/go-check-sumtype
```

nor 

```
go install github.com/alecthomas/go-check-sumtype/cmd/go-check-sumtype
```

seem to install a binary.

**Comment by alecthomas** [comment]
You need to append `@latest` since Go ~1.18 or so:

```
go install github.com/alecthomas/go-check-sumtype/cmd/go-check-sumtype@latest
```

**Comment by alecthomas** [comment]
FYI this will end up in `$GOBIN`, which you can find with `go env GOBIN`

**Comment by jeschkies** [comment]
Thanks for your quick reply. What do you think about having it in the README?
