### ISSUE TITLE
Configurable `default` case behaviour

### ISSUE THREAD

**Issue by lfportal** [alecthomas/go-check-sumtype#10]
The current behaviour of `default` case handling as I understand it is:

* if the block always results in a `panic`, all types must appear in a `case`
* if the block does not always result in a `panic`, treat this switch as "all cases handled"

I'd like to force all my switch cases to explicitly handle every case, regardless of the presence of a `default`. Whilst I could try to ensure every `default` results in a `panic`, this would have to be based on convention, and difficult to enforce with multiple contributors. Would you be open to accepting a PR that implements `default` handling in a configurable way?

**Comment by lfportal** [comment]
@alecthomas I've raised a PR here: #11

**Comment by alecthomas** [comment]
Fixed in #11
