### ISSUE TITLE
Exhaustiveness Check and Unreachable Case Clause collide

### ISSUE THREAD

**Issue by jeschkies** [alecthomas/go-check-sumtype#2]
I've found that the exhaustiveness check can collide with the [staticheck SA4020](https://staticcheck.dev/docs/checks/#SA4020).

In my case I have roughly the following

```go
type Expr interface {
    isExpr()
}

type SampleExpr interface {
    isExpr()
    isSampleExpr()
}

type Vector struct {}

func (v *Vector) isSampleExpr() {}
func (v *Vector) isExpr() {}

func walk(e Expr) {
    switch e {
        case SampleExpr:
            fmt.Println("sample")
    }
}
```
Here the check sumtype will fail. However, if I add the case for the vector

```go
func walk(e Expr) {
    switch e {
        case SampleExpr:
            fmt.Println("sample")
        case *Vector:
            fmt.Println("vector")
    }
}
```

staticcheck will fail. I think go-check-sumtype should take unreachable case clauses into account.

**Comment by alecthomas** [comment]
Why is it unreachable? What's the error?

**Comment by alecthomas** [comment]
Ah I see. I checked the link.

I don't think `go-check-sumtype` needs to duplicate this logic if `staticcheck` already does. It has a very specific task and this falls outside that scope.

**Comment by jeschkies** [comment]
> Why is it unreachable? What's the error?

Sorry, I've missed your comment. The `*Vector` is unreachable because the first case `SampleExpr` is matched. However, `go-check-sumtype` fails if the second case is not present. 

`go-check-sumtype` and `staticcheck` do not go together here. So one has to be ignored.
