### ISSUE TITLE
Check all packages even only packages with sum type declared are passed as arguments?

### ISSUE THREAD

**Issue by eyasy1217** [alecthomas/go-check-sumtype#4]
Hi.

if the sum type is declared in one package and the type switch is in a different package, If only packages with sum type declared are passed as arguments to the A command, it doesn't reported missing cases.
Is it possible to check all packages even only packages with sum type declared are passed as arguments?
For example,  by adding an option like `--find-all-packages`.🤔
In that case, the sum type defined in all packages would be undetected.

I am using this go-check-sumtype from golangci-lint and I am encountering the same problem as https://github.com/golangci/golangci-lint/issues/4158 .
Should I fix golangci-lint or this standalone in the first place?🤔

**Comment by alecthomas** [comment]
Are you sure the standalone tool exhibits this behaviour? IIUC it is an issue with how it's integrated into golangci-lint.

**Comment by alecthomas** [comment]
I verified that the tool works correctly, so it needs to be fixed in the downstream golangci-lint integration.
